var settings = {
  "help_en": "Show Statistics: !stats [Username] [Ship] - z.B.: !stats {player} {ship} - Hint: Shipname is optional",
  "help_de": "Stats anzeigen: !stats [Spielername] [Schiffsname] - z.B.: !stats {player} {ship} - Hinweis: Schiffsname ist optional",
  "stats_player_en": "Statistics of {player} --- Battles: {battles} || Average Damage: {avgDmg} || Winrate: {winrate}% --- Statuspage: {wgUrl}",
  "stats_player_de": "Statistik von {player} --- Gefechte: {battles} || Durchschn. Schaden: {avgDmg} || Winrate: {winrate}% --- Spielerseite: {wgUrl}",
  "stats_ships_en": "Statistics of {player} for {ship} --- Battles: {battles} || Average Damage: {avgDmg} || Winrate: {winrate}% --- Statuspage: {wgUrl}",
  "stats_ships_de": "Statistik von {player} für {ship} --- Gefechte: {battles} || Durchschn. Schaden: {avgDmg} || Winrate: {winrate}% --- Spielerseite: {wgUrl}",
  "hidden_player_en": "This player refuses to participate in Statshaming",
  "hidden_player_de": "Dieser Spieler weigert sich an der Statshaming-Kultur teilzuhaben",
  "unknown_player_en": "Player unknown",
  "unknown_player_de": "Spieler unbekannt",
  "unknown_ship_en": "Ship unknown",
  "unknown_ship_de": "Schiff unbekannt",
  "unknown_stats_en": "No statistics available",
  "unknown_stats_de": "Keine Statistiken bekannt",
  "missing_permission_en": "No Permission",
  "missing_permission_de": "Keine Berechtigung",
  "cooldown_message_en": "Command is still on cooldown",
  "cooldown_message_de": "Befehl ist noch auf Cooldown",
  "command": "!stats",
  "streamer": "Fuyu_Kitsune",
  "defaultShip": "Roma",
  "language": "de",
  "region": "eu",
  "appkey": ""
};